### PR TITLE
Add LOBPCG docs and bump docs/make.jl Julia version to v0.7

### PR DESCRIPTION
**Pull request by mohamed82008**
Please check if this is correct, I am not sure how to test it.

### CODE REVIEW

**Comment by haampie** [comment]
Fixes #211

**Comment by haampie** [comment]
> It also admits a preconditioner and a "constraints" matrix C, such that the algorithm returns the smallest (or largest) eigenvalues associated with the eigenvectors in the nullspace of C'B.

This does not really make sense to me

**Comment by mohamed82008** [comment]
The nullspace of A is all vectors x such that Ax = 0. This means that x is orthogonal to all the rows of A. If x is in the nullspace of C'B, then Bx is orthogonal to the rows of C', which are the columns of C. Or in other words, x is B-orthogonal to the columns of C. Long winded but correct :)

**Comment by haampie** [comment]
Yeah, sure, but the wording is not really what I'd expect in this context. You'd probably want to call it deflation. Also it leaves some questions open: Is C supposed to be B-orthogonal? In that case it really is deflation with (I - CC'B) the projection operator in the standard inner product.

**Pull request closed without merging**
