### PR TITLE
fix idrs! when near solution

### LINKED ISSUE #222: Error when initializing idrs! from [very near] solution
When initializing `idrs!` from near to the solution, I receive an error that res is not defined.  In looking closer, this is likely because `res` is referenced only on line 88 of idrs.jl and is not created anywhere. Line 88 is only called if `normR<=tol`, which is commented to occur when the "initial guess is a good enough solution."  Replacing the return value in this case to `X, log` seems to work fine for me, though this may be bad/breaking for other reasons. I thought I would report this here in case this or another solution would be an easy fix.  Thank you for putting this package together!

### PR DESCRIPTION
**Pull request by platawiec**
Fixes #222

### CODE REVIEW

**Comment by mschauer** [comment]
Looks good, even with a Test! Is any of the bookkeeping 
```
            shrink!(log)
	    setconv(log, 0<=normR<tol)
	    setmvps(log, iter)
```
needed/useful for this early break?

**Comment by platawiec** [comment]
Good point, I had a look. Only `setconv` seems necessary In fact, there was an extraneous call to `shrink!` which I removed.

**Comment by chriscoey** [comment]
bump

**Comment by mschauer** [comment]
bump?

**Comment by mschauer** [comment]
Planning to merge after the weekend.

**Pull request merged**
