### PR TITLE
add GitHub actions CI

### PR DESCRIPTION
**Pull request by ranocha**
This enables CI tests via GitHub actions since Travis CI will become annoying to use as discussed on Discourse (https://discourse.julialang.org/t/travis-ci-changes-pricing-plans/49528/14).

### CODE REVIEW

**Comment by ranocha** [comment]
I think the GitHub actions might be failing since the secrets

- `CODECOV_TOKEN`
- `COVERALLS_TOKEN`

for Coveralls and Codecov are not set. However, I don't have the necessary rights in this repo.

**Comment by ranocha** [comment]
I had to skip one test on two systems, probably because of different BLAS libraries and/or random number streams, resulting in a `SingularException`. Other than that, all tests pass on Linux, Windows, and MacOS in GitHub actions.

**Comment by haampie** [comment]
Hm, curious those tests are failing. I'll just merge this for now and get back to this flaky test. The proper solution would be to remove the singular components; maybe do an QR decomp. That's beyond the scope of this PR.

**Comment by ranocha** [comment]
Thanks!

**Pull request merged**
